# Generated by Django 2.1.7 on 2019-03-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='producto_subfamilia',
            new_name='producto_categoria',
        ),
    ]
