# Generated by Django 2.1.7 on 2019-03-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20190313_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_imagen',
            field=models.ImageField(default='images/none/nulo.png', upload_to='images/'),
        ),
    ]
