# Generated by Django 2.1.7 on 2019-03-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='producto_imagen',
            field=models.ImageField(default='/images/none/nulo.png', upload_to='images/'),
        ),
    ]
