# Generated by Django 2.1.7 on 2019-03-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20190313_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='producto_imagen',
            field=models.ImageField(default='/images/none/nulo.png', upload_to='images/productos'),
        ),
    ]
