# Generated by Django 2.1.7 on 2019-03-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20190315_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='categoria_imagen',
            field=models.ImageField(default='none/nulo.png', upload_to='categorias'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_imagen',
            field=models.ImageField(default='none/nulo.png', upload_to='productos'),
        ),
    ]
