# Generated by Django 2.1.7 on 2019-04-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_auto_20190422_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fecha_de_nacimiento',
            field=models.DateField(),
        ),
    ]
