# Generated by Django 2.1.7 on 2019-04-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_auto_20190423_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(default='none/sin-foto.jpg', upload_to='perfiles'),
        ),
    ]
